configuration:
  swagger:
    app: 'Course Application API'
    description: 'Course Application API for managing courses and students/admins via web interface'
    developer: 'Andrei Baranov'
    email: 'andrei.baranov@ibu.edu.ba'

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: courseApp

security:
  jwt:
    secret: 'AX0Tz7QUMGCuyC5i5jwpUkvu0JfQkVo1VNuUz8pF5sU'
    token:
      expire-length: 3600000
    refresh-token:
      expire-length: 28800000
  oauth2:
    client:
      registration:
        google:
          client-id: 369471357919-1o2fniv51qnkaaroeav0d2fct1ueudti.apps.googleusercontent.com
          client-secret: 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
          scope:
            - email
            - profile


website:
  frontend:
    url: 'http://localhost:5173'