configuration:
  swagger:
    app: 'Course Application API'
    description: 'Course Application API for managing courses and students/admins via web interface'
    developer: 'Andrei Baranov'
    email: 'andrei.baranov@ibu.edu.ba'

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: courseApp

security:
  jwt:
    secret: 'AX0Tz7QUMGCuyC5i5jwpUkvu0JfQkVo1VNuUz8pF5sU'
    token:
      expire-length: 3600000
    refresh-token:
      expire-length: 28800000

website:
  frontend:
    url: 'http://localhost:5173'